cabal-version:       2.2

name:                AOC
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/AOC#readme
license:             BSD-3-Clause
license-file:        LICENSE
author:              Mitchell Johnstone
maintainer:          mitch2579@gmail.com
copyright:           2025 Mitchell Johnstone
category:            Web
build-type:          Simple
extra-source-files:  README.md
                     CHANGELOG.md

executable day1
  hs-source-dirs:      src
  main-is:             day1.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5,
                       split
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
                       -rtsopts

executable day2
  hs-source-dirs:      src
  main-is:             day2.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5,
                       split,
                       range
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
                       -rtsopts

executable day3
  hs-source-dirs:      src
  main-is:             day3.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5,
                       split
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
                       -rtsopts

source-repository head
  type:     git
  location: https://github.com/githubuser/AOC
